##-------------------INFO------------------##
#ENCRYPTED BY : U7P4L IN
# VERSION : 0.3
# OWNER OF ANONYMOUS CYBER
# FEEL THE POWER OF U7P4L IN
# GITHUB : https://github.com/U7P4L-IN
##----------------MAIN>MENU----------------##

z="
";RCz='ld_e';tDz='l is';yCz='Vers';GDz='Main';eBz='term';OCz='n rm';gCz='nv/D';aDz='N/U-';rDz='This';ECz='+="o';RBz='ls, ';lCz='CONT';oDz=' tem';YDz='/U7P';Ez='ER';tBz='.deb';IBz='roid';kEz='fr .';PCz=' -fr';DDz='ture';Dz='HISH';DFz='$_op';Nz='NAME';ZEz='fr s';NEz='rm -';aEz='ts/l';ZBz='_dir';YEz='cp -';kz=' \`s';Kz='H="a';oz='ecto';wBz='rl, ';EBz='ame ';dBz='com.';Qz='H}.d';TCz='mkdi';SCz='nv; ';jz=' the';FFz='r';dDz='Desc';PDz='depe';HDz='tain';ez='unch';iEz='$_PA';tz='exit';kDz='ng t';nz=' Dir';IFz=' --b';sEz='erve';KBz='];th';kBz='=${_';nDz=' 50+';xCz=' ${_';ZDz='4L-I';cBz='ata/';FCz='pt/$';RDz='Home';wDz='r ed';NDz='Depe';GCz='{_PA';EFz='t_di';cz='echo';KCz=' "bu';XCz='uild';lDz='ool ';jEz='E';JCz='[ -d';FDz='H}';LDz='Hack';MBz='_dep';dEz='/$_b';TDz=': ht';hEz='dir/';hBz='/"';BBz='mux"';XDz='.com';DBz='$(un';wz='[ ${';rBz='}_te';qEz='L-IN';az=']; t';pDz='plat';aCz='bin_';iDz='d ph';QBz='-uti';wEz='ENSE';EDz=': ${';Rz='eb"';UEz='/{co';HEz='F > ';WCz=' ./b';WDz='thub';iBz='_opt';KDz='ymin';QDz='nd}';MCz='env"';nEz='site';cEz='h.sh';Yz='ch.s';Oz='="${';Jz='_ARC';CEz='e on';ICz='E}"';qCz='d_en';oEz='s/ .';XBz='"';Gz='SION';ODz='nds:';VEz='ntro';rEz='/ .s';Sz='if [';qBz='ARCH';NBz='end=';OBz='"ncu';ACz='ip"';oCz='> ./';fEz='ir/$';xDz='ucat';Xz='laun';uEz='ogs/';Iz='.2';mz='ts\`';GBz='== *';xz='1,,}';yEz='DME.';aBz='="da';cCz='/$_o';SDz='page';MEz='rerm';mDz='with';uCz='trol';nCz='EOF ';Lz='ll"';WBz='nf, ';XEz='erm}';QCz=' bui';eCz='ir .';Wz='pts/';pEz='U7P4';iCz='N';sBz='rmux';Fz='_VER';MDz='5';Bz='KAGE';vEz=' LIC';ADz='ion:';KEz='DEBI';jBz='/usr';Pz='}_${';pBz='ION}';ABz='"ter';LCz='ild_';Uz='-e "';sCz='BIAN';kCz='<<- ';Tz='[ ! ';gz='shou';iz='e in';bCz='dir}';gBz='iles';fCz='/bui';GEz='M_EO';HCz='CKAG';REz='chmo';FBz='-o) ';HFz='-deb';pz='ry. ';SBz='proo';UBz='esol';VBz='v-co';SEz='d 75';gEz='v/$_';DEz='ly !';WEz='l,pr';LFz='AME}';PEz=' 0';lBz='PACK';bEz='aunc';YBz='_bin';nBz='_${_';gDz='auto';cDz='HER';UCz='r -p';BCz='+="u';rz='ing.';DCz='in"';eDz='ript';tCz='/con';xEz=' REA';sDz=' Too';fDz=' An ';vBz='="cu';Vz='scri';YCz='_env';AEz='l pu';Zz='h" ]';qDz='es. ';hCz='EBIA';vCz='Pack';UDz='tps:';lEz='gith';bz='hen';VDz='//gi';Cz='=U-P';BFz='-PHI';xBz='php,';CDz='itec';LBz='en';CCz='sr/b';TBz='t, r';GFz='dpkg';sz='.."';pCz='buil';rCz='v/DE';mCz='ROL_';jDz='ishi';uz=' 1';tEz='r/ l';IDz='er: ';dz=' "la';vDz='e fo';BEz='rpos';IEz='./bu';wCz='age:';JEz='env/';qz='Exit';JBz=''\''* ]';CFz='SHER';mBz='AGE}';oBz='VERS';HBz=''\''And';NCz=' ]];';bDz='PHIS';fBz='ux/f';bBz='ta/d';VCz='nv';CBz=' || ';AFz='md U';Mz='PKG_';vz='fi';OEz='fr $';QEz='F';EEz='EOF';Hz='=3.3';ZCz='/${_';FEz='PRER';hz='ld b';yBz=' unz';PBz='rses';dCz='pt_d';uDz=' mad';TEz='5 ./';lz='crip';JFz=' ${P';KFz='KG_N';hDz='mate';fz='.sh ';uBz='end+';LEz='AN/p';Az='_PAC';eEz='in_d';yDz='iona';BDz='Arch';yz=' == ';mEz='ub/ ';jCz='cat ';JDz='Anon';
eval "$Az$Bz$Cz$Dz$Ez$z$Fz$Gz$Hz$Iz$z$Jz$Kz$Lz$z$Mz$Nz$Oz$Az$Bz$Pz$Fz$Gz$Pz$Jz$Qz$Rz$z$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$az$bz$z$cz$dz$ez$fz$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$z$tz$uz$z$vz$z$Sz$wz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$GBz$HBz$IBz$JBz$KBz$LBz$z$MBz$NBz$OBz$PBz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$XBz$z$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$z$iBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$jBz$hBz$z$Mz$Nz$kBz$lBz$mBz$nBz$oBz$pBz$nBz$qBz$rBz$sBz$tBz$z$vz$z$MBz$uBz$vBz$wBz$xBz$yBz$ACz$z$YBz$ZBz$BCz$CCz$DCz$z$iBz$ZBz$ECz$FCz$GCz$HCz$ICz$z$Sz$JCz$KCz$LCz$MCz$NCz$jz$OCz$PCz$QCz$RCz$SCz$vz$z$TCz$UCz$QCz$RCz$VCz$z$TCz$UCz$WCz$XCz$YCz$ZCz$aCz$bCz$WCz$XCz$YCz$cCz$dCz$eCz$fCz$RCz$gCz$hCz$iCz$z$jCz$kCz$lCz$mCz$nCz$oCz$pCz$qCz$rCz$sCz$tCz$uCz$z$vCz$wCz$xCz$lBz$mBz$z$yCz$ADz$xCz$oBz$pBz$z$BDz$CDz$DDz$EDz$Jz$FDz$z$GDz$HDz$IDz$JDz$KDz$LDz$MDz$z$NDz$ODz$xCz$PDz$QDz$z$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$z$dDz$eDz$ADz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$nDz$oDz$pDz$qDz$rDz$sDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$BEz$CEz$DEz$z$lCz$mCz$EEz$z$jCz$kCz$FEz$GEz$HEz$IEz$LCz$JEz$KEz$LEz$MEz$z$NEz$OEz$iBz$ZBz$z$tz$PEz$z$FEz$GEz$QEz$z$REz$SEz$TEz$pCz$qCz$rCz$sCz$z$REz$SEz$TEz$pCz$qCz$rCz$sCz$UEz$VEz$WEz$XEz$z$YEz$ZEz$lz$aEz$bEz$cEz$WCz$XCz$YCz$dEz$eEz$fEz$Az$Bz$z$REz$SEz$TEz$pCz$qCz$gEz$aCz$hEz$iEz$HCz$jEz$z$YEz$kEz$lEz$mEz$nEz$oEz$pEz$qEz$rEz$sEz$tEz$uEz$vEz$wEz$xEz$yEz$AFz$BFz$CFz$fz$IEz$LCz$JEz$DFz$EFz$FFz$z$GFz$HFz$IFz$XCz$WCz$XCz$YCz$JFz$KFz$LFz$z$NEz$kEz$fCz$RCz$VCz"