##-------------------INFO------------------##
#ENCRYPTED BY : U7P4L IN
# VERSION : 0.3
# OWNER OF ANONYMOUS CYBER
# FEEL THE POWER OF U7P4L IN
# GITHUB : https://github.com/U7P4L-IN
##----------------MAIN>MENU----------------##

z="
";NCz='}';Fz=' *'\''A';cz='HISH';VBz='iew ';LCz='exit';sBz='.U7P';BCz='dev/';Bz='[ $(';Sz='ermu';Ez=') ==';TCz='ev/n';mBz='s'\'' ]';gBz='elif';hz='PHIS';oBz='hen';KCz='"';PBz='nu &';dCz='bash';XCz='ed I';bCz='cd $';KBz='help';Cz='unam';yz='ype ';jBz='c'\'' |';aCz='!"';hCz='.sh';RCz='xt 2';gz='t/U-';gCz='SHER';GBz=' "He';yBz='txt ';YBz='eden';Qz='ta/c';Jz='then';Wz='opt/';Nz='OT="';nBz=']; t';xz='ER t';SCz='> /d';UBz=' : V';ZBz='tial';fBz=' IP"';lz=' == ';CCz='null';dBz='d Vi';oz='$1 =';wz=' U-P';ECz=' "No';ez='OOT=';Uz='les/';YCz='P Fo';EBz='r cm';mz=''\''-h'\''';fCz='-PHI';BBz='HER\';uBz='N/ww';pBz='cat ';TBz='logs';hBz=' [[ ';uz=' "To';QCz='ip.t';qBz='$U-P';HBz='lp:"';XBz='d Cr';rz=' the';iBz='= '\''-';FCz=' Cre';vz=' run';HCz='ials';CBz='` in';Rz='om.t';Gz='ndro';Hz='id'\''*';MBz='rint';Pz='a/da';tz='echo';kz='[ $1';az='rt A';JBz='h | ';tBz='4L-I';Lz='ISHE';OCz='i'\'' |';ACz='2> /';VCz='|| {';Az='if [';MCz=' 1';UCz='ull ';FBz='d "';pz='= '\''h';vBz='w/us';QBz=' Exi';bBz='i | ';iz='HER"';bz='NONP';IBz=' " -';Zz='expo';WBz='Save';ABz='\`U-';jz='fi';Xz='R"';lBz=''\''log';qz='elp'\''';fz='"/op';Yz='else';Mz='R_RO';RBz='t"';LBz=' : P';SBz='c | ';dz='ER_R';kBz='| $1';wBz='erna';nz=' || ';eBz='ctim';cCz='OT';ICz=' Fou';OBz='s me';GCz='dent';Kz='U-PH';cBz='ip  ';Tz='x/fi';JCz='nd !';WCz=' Sav';eCz=' ./U';sz='n';Oz='/dat';Iz=' ]];';rBz='OOT/';NBz=' thi';Vz='usr/';Dz='e -o';ZCz='und ';xBz='mes.';DBz=' you';PCz=''\''ip'\''';DCz='{';aBz='s"';
eval "$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$z$Kz$Lz$Mz$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Kz$Lz$Xz$z$Yz$z$Zz$az$bz$cz$dz$ez$fz$gz$hz$iz$z$jz$z$Az$kz$lz$mz$nz$oz$pz$qz$Iz$rz$sz$z$tz$uz$vz$wz$cz$xz$yz$ABz$hz$BBz$CBz$DBz$EBz$FBz$z$tz$z$tz$GBz$HBz$z$tz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$z$tz$IBz$SBz$TBz$UBz$VBz$WBz$XBz$YBz$ZBz$aBz$z$tz$IBz$bBz$cBz$UBz$VBz$WBz$dBz$eBz$fBz$z$tz$z$gBz$hBz$oz$iBz$jBz$kBz$lz$lBz$mBz$nBz$oBz$z$pBz$qBz$cz$dz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$ACz$BCz$CCz$nz$DCz$z$tz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$z$LCz$MCz$z$NCz$z$gBz$hBz$oz$iBz$OCz$kBz$lz$PCz$Iz$rz$sz$z$pBz$qBz$cz$dz$rBz$QCz$RCz$SCz$TCz$UCz$VCz$z$tz$ECz$WCz$XCz$YCz$ZCz$aCz$z$LCz$MCz$z$NCz$z$Yz$z$bCz$Kz$Lz$Mz$cCz$z$dCz$eCz$fCz$gCz$hCz$z$jz"